apiVersion: apps/v1
kind: Deployment
metadata:
  name: stiction-frontend
  labels:
    app: stiction-frontend

spec:
  replicas: 1

  selector:
    matchLabels:
      app: stiction-frontend

  template:
    metadata:
      labels:
        app: stiction-frontend

    spec:
      containers:
        - name: stiction-frontend
          image: stiction-deep-coral-frontend:v1
          imagePullPolicy: IfNotPresent

          ports:
            - containerPort: 8501

          env:
            - name: FASTAPI_URL
              value: "http://stiction-api-service:8000"

          readinessProbe:
            tcpSocket:
              port: 8501
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 6

          livenessProbe:
            tcpSocket:
              port: 8501
            initialDelaySeconds: 20
            periodSeconds: 20
            timeoutSeconds: 5
            failureThreshold: 3

          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
