apiVersion: v1
kind: Service
metadata:
  name: stiction-frontend-service

spec:
  selector:
    app: stiction-frontend

  ports:
    - name: http
      protocol: TCP
      port: 8501
      targetPort: 8501

  type: ClusterIP
